[package]
name = "actix_send"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"
exclude = ["examples/*"]
readme = "README.md"

[lib]
name = "actix_send"
path = "src/lib.rs"

[workspace]
members = [
    "actix-send-macros",
]

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "concurrency"
path = "examples/concurrency.rs"

[[example]]
name = "no_macro"
path = "examples/no_macro.rs"

[features]
default = ["tokio-runtime"]
tokio-runtime = ["tokio/rt-threaded", "tokio/sync", "tokio/time"]
async-std-runtime = ["async-std", "tokio/sync"]

[dependencies]
actix_send_macros = { path = "./actix-send-macros" }
async-channel = "1.1.0"
async-trait = "0.1.35"
futures = { version = "0.3.5", default-features = false, features = ["alloc"] }
parking_lot = "0.11.0"

async-std = { version = "1.6.2", optional = true, default-features = false }
tokio = { version = "0.2.21", optional = true, default-features = false }

[dev-dependencies]
async-std = { version = "1.6.2", features = ["unstable"] }
tokio-test = { git = "https://github.com/tokio-rs/tokio" }
tokio = { version = "0.2.21", features = ["full"] }
actix = ""
actix-rt = ""
num_cpus = ""