[package]
name = "actix_send"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"
exclude = ["examples/*"]

[lib]

[workspace]
members = [
    "actix-send-macros",
]

[[example]]
name = "basic"
path = "examples/basic.rs"

[features]
default = ["tokio-runtime"]
tokio-runtime = ["tokio/rt-threaded", "tokio/sync"]
async-std-runtime = ["async-std", "tokio/sync"]

[dependencies]
actix_send_macros = { path = "actix-send-macros" }
async-channel = { git = "https://github.com/stjepang/async-channel" }
async-trait = "0.1.35"
futures-channel = { version = "0.3.5" }

async-std = { version = "1.6.1", optional = true }
tokio = { version = "0.2.21", optional = true, default-features = false }

[dev-dependencies]
tokio = { version = "0.2.21", features = ["rt-threaded", "macros"] }
async-std = { version = "1.6.1", features = ["unstable"] }