[package]
name = "actix_send"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"
exclude = ["examples/*"]
readme = "README.md"

[lib]
name = "actix_send"
path = "src/lib.rs"

[workspace]
members = [
    "actix-send-macros",
]

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "benchmark"
path = "examples/benchmark.rs"

[[example]]
name = "blocking"
path = "examples/blocking.rs"

[[example]]
name = "concurrency"
path = "examples/concurrency.rs"

[[example]]
name = "delayed_message"
path = "examples/delayed_message.rs"

[[example]]
name = "dynamic_dispatch"
path = "examples/dynamic_dispatch.rs"

[[example]]
name = "no_macro"
path = "examples/no_macro.rs"

[[example]]
name = "stream"
path = "examples/stream.rs"

[[example]]
name = "type_alias"
path = "examples/type_alias.rs"

[features]
default = ["tokio-runtime"]
tokio-runtime = ["tokio/rt-threaded", "tokio/stream", "tokio/sync", "tokio/time"]
async-std-runtime = ["async-std", "tokio/sync"]
actix-runtime = ["actix-rt", "tokio/sync"]

[dependencies]
actix_send_macros = { path = "./actix-send-macros" }
async-channel = "1.1.0"
async-trait = "0.1.36"
futures-util = { version = "0.3.5", default-features = false }
pin-project = "0.4.22"

actix-rt = { version = "1.1.1", optional = true }
async-std = { version = "1.6.2", optional = true, default-features = false }
tokio = { version = "0.2.21", optional = true, default-features = false }

[dev-dependencies]
actix = "0.10.0-alpha.3"
actix-rt = "1.1.1"
async-std = { version = "1.6.2", features = ["attributes", "unstable"] }
tokio = { version = "0.2.21", features = ["full"] }
num_cpus = ""