[package]
name = "actix_send_websocket"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"

[features]
default = ["actix_send/actix-runtime-local"]
send = ["actix_send/actix-runtime"]

[dependencies]
actix-codec = "0.2.0"
actix-http = "2.0.0-beta.3"
actix_send = { git = "https://github.com/fakeshadow/actix_send.git", default-features = false, optional = true }
actix-web = "3.0.0-beta.3"
futures-channel = { version = "0.3.5", default-features = false }
futures-util = { version = "0.3.5", default-features = false }
pin-project = "0.4.23"