[package]
name = "actix_send_macros"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.19"
quote = "1.0.7"
syn = { version = "1.0.38", features = ["extra-traits", "full"] }
